#!/usr/bin/env bash
# A npm wrapper to be logged in in npm (ie release)
# release that injects the env
# and run yarn release-it

set -Eeuo pipefail
skip_check=false

for arg in "$@"; do
    if [[ "$arg" == "--no-check" ]]; then
        skip_check=true
    fi
done

if [[ "$skip_check" == false ]]; then
    echo "Running check..."
    yarn check
else
    echo "Skipping check (--no-check passed)"
fi

# You also need the NPM_TOKEN

export GITHUB_TOKEN
GITHUB_TOKEN=$(pass github/gh-token)

# run with --dry-run
yarn release-it "$@"
