#!/usr/bin/env bash
# A npm wrapper to be logged in in npm (ie release)
# release that injects the env
# and run yarn release-it

set -Eeuo pipefail
skip_check=true

for arg in "$@"; do
    if [[ "$arg" == "--check" ]]; then
        skip_check=false
    fi
done

if [[ "$skip_check" == false ]]; then
    echo "Running check..."
    yarn workspace @combostrap/interact check
else
    echo "Skipping check (no --check passed)"
fi

# We also need the NPM_TOKEN
# passed in .npmrc with this line:
# //registry.npmjs.org/:_authToken=${NPM_TOKEN}
export NPM_TOKEN
NPM_TOKEN=$(pass npm/release-token)

export GITHUB_TOKEN
GITHUB_TOKEN=$(pass github/gh-token)

# Without args, it will ask question
echo "command: yarn workspace @combostrap/interact release-it $*"
yarn workspace @combostrap/interact release-it "$@"
